-- PostgreSQL production schema. The exclusion constraint is the concurrency safeguard: application
-- checks provide useful conflict details, while PostgreSQL serializes simultaneous writes.
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE IF NOT EXISTS reservations (
    id uuid PRIMARY KEY,
    room_id uuid NOT NULL,
    member_id uuid NOT NULL,
    starts_at_utc timestamptz NOT NULL,
    ends_at_utc timestamptz NOT NULL,
    is_cancelled boolean NOT NULL DEFAULT false,
    CHECK (ends_at_utc > starts_at_utc)
);

CREATE INDEX IF NOT EXISTS ix_reservations_room_time
    ON reservations (room_id, starts_at_utc, ends_at_utc);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'reservations_no_active_overlap'
    ) THEN
        ALTER TABLE reservations
            ADD CONSTRAINT reservations_no_active_overlap
            EXCLUDE USING gist (
                room_id WITH =,
                tstzrange(starts_at_utc, ends_at_utc, '[)') WITH &&
            ) WHERE (is_cancelled = false);
    END IF;
END $$;

-- ASP.NET Core Identity schema. This is provisioned in the same startup step as the
-- reservation schema so identity endpoints cannot be exposed before their tables exist.
CREATE TABLE IF NOT EXISTS members (
    "Id" uuid PRIMARY KEY,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex"
    ON members ("NormalizedUserName");

CREATE INDEX IF NOT EXISTS "EmailIndex"
    ON members ("NormalizedEmail");

CREATE TABLE IF NOT EXISTS roles (
    "Id" uuid PRIMARY KEY,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);

CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex"
    ON roles ("NormalizedName");

CREATE TABLE IF NOT EXISTS member_claims (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "FK_member_claims_members_UserId"
        FOREIGN KEY ("UserId") REFERENCES members ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_member_claims_UserId"
    ON member_claims ("UserId");

CREATE TABLE IF NOT EXISTS member_logins (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_member_logins"
        PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_member_logins_members_UserId"
        FOREIGN KEY ("UserId") REFERENCES members ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_member_logins_UserId"
    ON member_logins ("UserId");

CREATE TABLE IF NOT EXISTS member_roles (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_member_roles"
        PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_member_roles_members_UserId"
        FOREIGN KEY ("UserId") REFERENCES members ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_member_roles_roles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES roles ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_member_roles_RoleId"
    ON member_roles ("RoleId");

CREATE TABLE IF NOT EXISTS role_claims (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "FK_role_claims_roles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES roles ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_role_claims_RoleId"
    ON role_claims ("RoleId");

CREATE TABLE IF NOT EXISTS member_tokens (
    "UserId" uuid NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text,
    CONSTRAINT "PK_member_tokens"
        PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_member_tokens_members_UserId"
        FOREIGN KEY ("UserId") REFERENCES members ("Id") ON DELETE CASCADE
);
