<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><TreatWarningsAsErrors>true</TreatWarningsAsErrors></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Roombook.Reservations\Roombook.Reservations.csproj" />
    <ProjectReference Include="..\Roombook.Rooms\Roombook.Rooms.csproj" />
    <ProjectReference Include="..\Roombook.Infrastructure\Roombook.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
</Project>
